//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public Nullable<int> UserSubjectID { get; set; }
        public string TutorID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Hour { get; set; }
        public string ComplainFromUser { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusID { get; set; }
        public byte[] FileContract { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
