//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubject
    {
        public string UserId { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Rank_ID { get; set; }
        public int ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
