//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSkillsLevel
    {
        public string User_ID { get; set; }
        public Nullable<int> Skill_ID { get; set; }
        public Nullable<int> Level_ID { get; set; }
    }
}
